package com.yourname.demo.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.yourname.demo.model.DemoTest;
 
/**
 * DAO interface for table: DemoTest.
 * @author autogenerated
 */
public interface DemoTestDao extends GenericDAO<DemoTest,  Integer>  {
	// constructor only
}

