package com.yourname.demo.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.yourname.demo.model.DemoTest;
import org.springframework.stereotype.Repository;
import com.yourname.demo.model.dao.DemoTestDao;
 
 
/**
 * DAO for table: DemoTest.
 * @author autogenerated
 */
@Repository
public class DemoTestDaoImpl extends GenericHibernateDaoImpl<DemoTest, Integer> implements DemoTestDao {
	
	/** Constructor method. */
		public DemoTestDaoImpl() {
			super(DemoTest.class);
		}
	}

