package com.yourname.demo.model.factories;

import com.yourname.demo.model.*;
import org.springframework.stereotype.Component;

import com.google.common.collect.ArrayListMultimap;
import com.google.common.collect.Multimap;
import java.util.Collection;
import com.felees.hbnpojogen.randomlib.data.dataGeneration.BasicDataGenerator;


/** 
 * DAO factory implementation.
 * @author autogenerated
 */
@Component
public class SchedulerDataPoolFactory {
	/** Table commit order. */
    private static final Multimap<String, String> tableDeps = ArrayListMultimap.create();
	/** DB commit order. */
	private static final String[] commitOrder = new String[]{"DemoTest"};
	static{
		// Store table deps for possible use. 
	}

    /**
     * Data pool factory for DemoTest.
     * @return DemoTestA DemoTest object
     */
    public static DemoTest getDemoTest() {

        DemoTest demoTest = new DemoTest();    
        
        demoTest.setName(BasicDataGenerator.generateRandomString(45));

        return demoTest;
    }
    /** Returns the commit order of this database. 
	 * Useful for iterating through the classes for deletion in the right order. 
	 * @return String[] list of classes
	 */
	public static String[] getDBCommitOrder() {
		return commitOrder;
	}
	
	/**
	 * @param className classname to return
	 * @return the tabledeps for the given class name
	 */
	public static Collection<String> getTabledeps(String className) {
		return tableDeps.get(className);
	}
	
}
